version: '3.1'
services:
  db:
    image: mariadb
    container_name: bbs_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD} 
    ports:
      - 3306:3306
    volumes:
      - './data:/var/lib/mysql'